### ISSUE TITLE
F1 score

### ISSUE THREAD

**Issue by chetan1836** [oldoldalf/FlowScope#1]
How to obtain precision, recall and f1_score.

**Comment by aplaceof** [comment]
I wish you could stop, anti-money laundering(AML) is useless. you can search the top AML company，such as LexisNexis(it has some business about AML ),  Analysing its annual report，you will know that devote your career to AML is a total mistake.   Maybe, a job of software engineer is a better choice. 

    If a person can build a car, why he choose to repair a car？Do you think this man  some how was not smart.  Yes back to this question, the most import thing in a company is profit, if the work you do is related to the core profits, your payment, your feature will be brighter, if you do other jobs, you are insignificant, the meaning of your existence is only to support the core department. 

   In the bank, why you choose AML, the core business of the bank is loan business. AML does not create any  direct  profit for the bank, so  if the government not force the bank do some AML, you existence have no value.  There are so many better job than AML in bank, such as software engineer, make a profit, get pay.  You can learning about the salary of AML job, you will know I am suggesting you for a better feature. 

I am work so long with this in the school, and has no prejudice about this research before, but when I am about to graduate and want to find a job, I realized it was a big mistake, I can not find good internship,  good job, my classmates gets several times  salary than me. Even I work hard than them in the school, even they play game everyday.  Once, a  human resource throws my CV onto my face at once after browse it, I really don't know where I went wrong， and I spent countless sleepless night during my last year in the school. All of above is the total truth that I experienced, I hope you do not follow my path. It was totally wrong. 

Stop doing this  !!!!!!!!!!!!!!!!!!!!!!!!!!!!  Software engineer is a better choice !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     

if you do not believe me, looking at the  annual report of the parent company of  LexisNexis， RELX， it was easy to find. LexisNexis is top company  in AML,  its mainly business operators in Europe and North America, where the financial system is quite mature in financial markets, and the governments pay more attention to the AML problem.  It total revenue about risk solution and  business analytics is only 2,316 million ￡,   the AML's revenue is just a part of it, showing as the picture below.

![image](https://user-images.githubusercontent.com/59363655/90001747-66864e00-dcc4-11ea-9f27-257c299feed6.png)

Stop doing this  !!!!!!!!!!!!!!!!!!!!!!!!!!!!  Software engineer is a better choice !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by aplaceof** [comment]
> How to obtain precision, recall and f1_score.

   I wish you could stop, anti-money laundering(AML) is useless. you can search the top AML company，such as LexisNexis(it has some business about AML ),  Analysing its annual report，you will know that devote your career to AML is a total mistake.   Maybe, a job of software engineer is a better choice. 

    If a person can build a car, why he choose to repair a car？Do you think this man  some how was not smart.  Yes back to this question, the most import thing in a company is profit, if the work you do is related to the core profits, your payment, your feature will be brighter, if you do other jobs, you are insignificant, the meaning of your existence is only to support the core department. 

   In the bank, why you choose AML, the core business of the bank is loan business. AML does not create any  direct  profit for the bank, so  if the government not force the bank do some AML, you existence have no value.  There are so many better job than AML in bank, such as software engineer, make a profit, get pay.  You can learning about the salary of AML job, you will know I am suggesting you for a better feature. 

I am work so long with this in the school, and has no prejudice about this research before, but when I am about to graduate and want to find a job, I realized it was a big mistake, I can not find good internship,  good job, my classmates gets several times  salary than me. Even I work hard than them in the school, even they play game everyday.  Once, a  human resource throws my CV onto my face at once after browse it, I really don't know where I went wrong， and I spent countless sleepless night during my last year in the school. All of above is the total truth that I experienced, I hope you do not follow my path. It was totally wrong. 

Stop doing this  !!!!!!!!!!!!!!!!!!!!!!!!!!!!  Software engineer is a better choice !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!     

if you do not believe me, looking at the  annual report of the parent company of  LexisNexis， RELX， it was easy to find. LexisNexis is top company  in AML,  its mainly business operators in Europe and North America, where the financial system is quite mature in financial markets, and the governments pay more attention to the AML problem.  It total revenue about risk solution and  business analytics is only 2,316 million ￡,   the AML's revenue is just a part of it, showing as the picture below.

![image](https://user-images.githubusercontent.com/59363655/90001747-66864e00-dcc4-11ea-9f27-257c299feed6.png)

Stop doing this  !!!!!!!!!!!!!!!!!!!!!!!!!!!!  Software engineer is a better choice !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
