### ISSUE TITLE
A question about greedy.py

### ISSUE THREAD

**Issue by galoispure** [oldoldalf/FlowScope#2]
in greedy.py line 162-176:
"
                new_mid_value = midTree1.changeVal(j, -M1[nextRow, j])

                if new_mid_value == float('inf'):
                    continue
                temp_mid2 = midTree2.index_of(j)
                mid_min_value = min( new_mid_value ,temp_mid2 )
                mid_delta_value = abs(new_mid_value - temp_mid2)
                new_mid_value = mid_min_value  - alpha * mid_delta_value
                new_mid_tree.setter( j , new_mid_value )

                if (new_mid_value) < mid_min[j]:  # if new_mid_value  of node j < min_mid_value  of node j
                    curScore1 -= (mid_min[j] - new_mid_value)
                    mid_min[j] = new_mid_value

                curScore2 = curScore2 - abs(midDeltas1[j] - midDeltas2[j])
                curScore2 = curScore2 + abs(new_mid_value - midDeltas2[j])
                midDeltas1[j] = new_mid_value
"
Fisrtly "new_mid_value" is set to new in flow amount. Then update by "new_mid_value = mid_min_value  - alpha * mid_delta_value".
why can this "new_mid_value" can be used to update mid_min, curScore1, curScore2 and midDeltas1?
It's confusing.
Should we update the "new_mid_value" after the calculation of  "mid_min, curScore1, curScore2 and midDeltas1"?

The same issue for "col" part.

**Comment by oldoldalf** [comment]
> in greedy.py line 162-176:
> "
> new_mid_value = midTree1.changeVal(j, -M1[nextRow, j])
> 
> ```
>             if new_mid_value == float('inf'):
>                 continue
>             temp_mid2 = midTree2.index_of(j)
>             mid_min_value = min( new_mid_value ,temp_mid2 )
>             mid_delta_value = abs(new_mid_value - temp_mid2)
>             new_mid_value = mid_min_value  - alpha * mid_delta_value
>             new_mid_tree.setter( j , new_mid_value )
> 
>             if (new_mid_value) < mid_min[j]:  # if new_mid_value  of node j < min_mid_value  of node j
>                 curScore1 -= (mid_min[j] - new_mid_value)
>                 mid_min[j] = new_mid_value
> 
>             curScore2 = curScore2 - abs(midDeltas1[j] - midDeltas2[j])
>             curScore2 = curScore2 + abs(new_mid_value - midDeltas2[j])
>             midDeltas1[j] = new_mid_value
> ```
> 
> "
> Fisrtly "new_mid_value" is set to new in flow amount. Then update by "new_mid_value = mid_min_value - alpha * mid_delta_value".
> why can this "new_mid_value" can be used to update mid_min, curScore1, curScore2 and midDeltas1?
> It's confusing.
> Should we update the "new_mid_value" after the calculation of "mid_min, curScore1, curScore2 and midDeltas1"?
> 
> The same issue for "col" part.

Stop read this fucking code,  do something  useful or meaningful. See my answer in

**Comment by galoispure** [comment]
> > in greedy.py line 162-176:
> > "
> > new_mid_value = midTree1.changeVal(j, -M1[nextRow, j])
> > ```
> >             if new_mid_value == float('inf'):
> >                 continue
> >             temp_mid2 = midTree2.index_of(j)
> >             mid_min_value = min( new_mid_value ,temp_mid2 )
> >             mid_delta_value = abs(new_mid_value - temp_mid2)
> >             new_mid_value = mid_min_value  - alpha * mid_delta_value
> >             new_mid_tree.setter( j , new_mid_value )
> > 
> >             if (new_mid_value) < mid_min[j]:  # if new_mid_value  of node j < min_mid_value  of node j
> >                 curScore1 -= (mid_min[j] - new_mid_value)
> >                 mid_min[j] = new_mid_value
> > 
> >             curScore2 = curScore2 - abs(midDeltas1[j] - midDeltas2[j])
> >             curScore2 = curScore2 + abs(new_mid_value - midDeltas2[j])
> >             midDeltas1[j] = new_mid_value
> > ```
> > 
> > 
> > "
> > Fisrtly "new_mid_value" is set to new in flow amount. Then update by "new_mid_value = mid_min_value - alpha * mid_delta_value".
> > why can this "new_mid_value" can be used to update mid_min, curScore1, curScore2 and midDeltas1?
> > It's confusing.
> > Should we update the "new_mid_value" after the calculation of "mid_min, curScore1, curScore2 and midDeltas1"?
> > The same issue for "col" part.
> 
> Stop read this fucking code, do something useful or meaningful. See my understanding of anti money laundering after I do this work for 2 years at [#1 (comment)](https://github.com/oldoldalf/FlowScope/issues/1#issuecomment-672779832) .
> I hope you can stop, and get a better feature. Stop doing this fucking work.

To my surprise, you answer my question in this way.

You'd better prove your work. At least, make it correct as your statement.
Otherwise, no one can believe you have done a good job in your graduate program.

I agree If you want to get a job with a high salary, AML is not a good choice. 
Anyway, wish you had a good start of your career.

**Comment by oldoldalf** [comment]
> > > in greedy.py line 162-176:
> > > "
> > > new_mid_value = midTree1.changeVal(j, -M1[nextRow, j])
> > > ```
> > >             if new_mid_value == float('inf'):
> > >                 continue
> > >             temp_mid2 = midTree2.index_of(j)
> > >             mid_min_value = min( new_mid_value ,temp_mid2 )
> > >             mid_delta_value = abs(new_mid_value - temp_mid2)
> > >             new_mid_value = mid_min_value  - alpha * mid_delta_value
> > >             new_mid_tree.setter( j , new_mid_value )
> > > 
> > >             if (new_mid_value) < mid_min[j]:  # if new_mid_value  of node j < min_mid_value  of node j
> > >                 curScore1 -= (mid_min[j] - new_mid_value)
> > >                 mid_min[j] = new_mid_value
> > > 
> > >             curScore2 = curScore2 - abs(midDeltas1[j] - midDeltas2[j])
> > >             curScore2 = curScore2 + abs(new_mid_value - midDeltas2[j])
> > >             midDeltas1[j] = new_mid_value
> > > ```
> > > 
> > > 
> > > "
> > > Fisrtly "new_mid_value" is set to new in flow amount. Then update by "new_mid_value = mid_min_value - alpha * mid_delta_value".
> > > why can this "new_mid_value" can be used to update mid_min, curScore1, curScore2 and midDeltas1?
> > > It's confusing.
> > > Should we update the "new_mid_value" after the calculation of "mid_min, curScore1, curScore2 and midDeltas1"?
> > > The same issue for "col" part.
> > 
> > 
> > Stop read this fucking code, do something useful or meaningful. See my understanding of anti money laundering after I do this work for 2 years at [#1 (comment)](https://github.com/oldoldalf/FlowScope/issues/1#issuecomment-672779832) .
> > I hope you can stop, and get a better feature. Stop doing this fucking work.
> 
> To my surprise, you answer my question in this way.
> 
> You'd better prove your work. At least, make it correct as your statement.
> Otherwise, no one can believe you have done a good job in your graduate program.
> 
> I agree If you want to get a job with a high salary, AML is not a good choice.
> Anyway, wish you had a good start of your career.

Sorry for being so rude, thanks for your suggestion, and I will fix the problem quickly.  
And I've already got a job, Thank you for your blessings.  
People always say that Europe was strict and precise in  academic research,  and it's my honor to see your high responsibility.

**Comment by aplaceof** [comment]
> > > > in greedy.py line 162-176:
> > > > "
> > > > new_mid_value = midTree1.changeVal(j, -M1[nextRow, j])
> > > > ```
> > > >             if new_mid_value == float('inf'):
> > > >                 continue
> > > >             temp_mid2 = midTree2.index_of(j)
> > > >             mid_min_value = min( new_mid_value ,temp_mid2 )
> > > >             mid_delta_value = abs(new_mid_value - temp_mid2)
> > > >             new_mid_value = mid_min_value  - alpha * mid_delta_value
> > > >             new_mid_tree.setter( j , new_mid_value )
> > > > 
> > > >             if (new_mid_value) < mid_min[j]:  # if new_mid_value  of node j < min_mid_value  of node j
> > > >                 curScore1 -= (mid_min[j] - new_mid_value)
> > > >                 mid_min[j] = new_mid_value
> > > > 
> > > >             curScore2 = curScore2 - abs(midDeltas1[j] - midDeltas2[j])
> > > >             curScore2 = curScore2 + abs(new_mid_value - midDeltas2[j])
> > > >             midDeltas1[j] = new_mid_value
> > > > ```
> > > > 
> > > > 
> > > > "
> > > > Fisrtly "new_mid_value" is set to new in flow amount. Then update by "new_mid_value = mid_min_value - alpha * mid_delta_value".
> > > > why can this "new_mid_value" can be used to update mid_min, curScore1, curScore2 and midDeltas1?
> > > > It's confusing.
> > > > Should we update the "new_mid_value" after the calculation of "mid_min, curScore1, curScore2 and midDeltas1"?
> > > > The same issue for "col" part.
> > > 
> > > 
> > > Stop read this fucking code, do something useful or meaningful. See my understanding of anti money laundering after I do this work for 2 years at [#1 (comment)](https://github.com/oldoldalf/FlowScope/issues/1#issuecomment-672779832) .
> > > I hope you can stop, and get a better feature. Stop doing this fucking work.
> > 
> > 
> > To my surprise, you answer my question in this way.
> > You'd better prove your work. At least, make it correct as your statement.
> > Otherwise, no one can believe you have done a good job in your graduate program.
> > I agree If you want to get a job with a high salary, AML is not a good choice.
> > Anyway, wish you had a good start of your career.
> 
> Sorry for being so rude, thanks for your suggestion, and I will fix the problem quickly.
> And I've already got a job, Thank you for your blessings.
> People always say that Europe was strict and precise in academic research, thanks for your high sense of responsibility.



> in greedy.py line 162-176:
> "
> new_mid_value = midTree1.changeVal(j, -M1[nextRow, j])
> 
> ```
>             if new_mid_value == float('inf'):
>                 continue
>             temp_mid2 = midTree2.index_of(j)
>             mid_min_value = min( new_mid_value ,temp_mid2 )
>             mid_delta_value = abs(new_mid_value - temp_mid2)
>             new_mid_value = mid_min_value  - alpha * mid_delta_value
>             new_mid_tree.setter( j , new_mid_value )
> 
>             if (new_mid_value) < mid_min[j]:  # if new_mid_value  of node j < min_mid_value  of node j
>                 curScore1 -= (mid_min[j] - new_mid_value)
>                 mid_min[j] = new_mid_value
> 
>             curScore2 = curScore2 - abs(midDeltas1[j] - midDeltas2[j])
>             curScore2 = curScore2 + abs(new_mid_value - midDeltas2[j])
>             midDeltas1[j] = new_mid_value
> ```
> 
> "
> Fisrtly "new_mid_value" is set to new in flow amount. Then update by "new_mid_value = mid_min_value - alpha * mid_delta_value".
> why can this "new_mid_value" can be used to update mid_min, curScore1, curScore2 and midDeltas1?
> It's confusing.
> Should we update the "new_mid_value" after the calculation of "mid_min, curScore1, curScore2 and midDeltas1"?
> 
> The same issue for "col" part.

Some day, you need money, or suffer from  poverty, or you family members sicking in bed, you will know the importance of a high pay. I hope that will never happen.  You have a good paper, what's the matter with the company and others people, it can drink, eat or translate into money? 
You are young  and may not  get fucked by society and life, if you were, you will know what I am saying and complaining.
